version: '3'

services:
  cosmovisor:
    container_name: cosmovisor
    image: "us-central1-docker.pkg.dev/octopus-prod/octopus-appchains/oyster@sha256:d3cd84900f821953fc460b8ae8418532c6f76f6f777e17550ddc0d3c1075376b"
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - /data:/data:Z
    command:
      - /bin/bash -c "/data/init_and_start.sh"