name: Lint
on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          skip-pkg-cache: true
          go-version: "1.20"    
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v3.6.0
        with:
          skip-pkg-cache: true
          args: --timeout=3m
          version: latest
        # Check only if there are differences in the source code
        if: "env.GIT_DIFF"                    
